# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Update with your branch name

pool:
  vmImage: 'windows-latest'  # Use a Windows agent

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'YourAzureServiceConnection'  # Azure service connection name
    ScriptType: 'InlineScript'
    Inline: |
      # Your PowerShell script to execute on the Windows VM
      # Example: Remote PowerShell command to create a folder on the VM
      $username = 'YourVMUsername'
      $password = 'YourVMPassword' | ConvertTo-SecureString -AsPlainText -Force
      $credential = New-Object System.Management.Automation.PSCredential($username, $password)
      $session = New-PSSession -ComputerName 'YourVMIPAddress' -Credential $credential
      Invoke-Command -Session $session -ScriptBlock {
        New-Item -ItemType Directory -Path 'C:\YourFolderPath'
      }
    azurePowerShellVersion: 'LatestVersion'
